### ISSUE TITLE
如何生成index.html文件呢？

### ISSUE THREAD

**Issue by luckypoem** [qibin0506/TitanPages#1]
hi。

http://104.255.35.132:2347/

不知如何生成index.html文件呢？

**Comment by qibin0506** [comment]
index.html需要自己编写的， 在index.html中引用category.auto.js文件,通过get(page)函数去获取当前页的数据， 详细介绍可以看：[http://blog.csdn.net/qibin0506/article/details/51813428](http://blog.csdn.net/qibin0506/article/details/51813428)

**Comment by luckypoem** [comment]
hi.

我复制了~/TitanPages/demo/make/html/里面所有的html文件到my_blog/html/里面，
复制了~/TitanPages/demo/make/html/category.auto.js文件到my_blog/js/里面。
不过首页http://104.255.35.132:2348/ 只显示了一篇帖子，未显示其他帖子，如何解决？
http://104.255.35.132:2348/html/ 里显示了其他的帖子。

**Comment by luckypoem** [comment]
怪事，现在所有帖子都可显示

**Comment by qibin0506** [comment]
[http://104.255.35.132:2348/html/%E5%94%90%E5%B1%B1%E5%A4%A7%E5%9C%B0%E9%9C%87%E7%9C%9F%E7%9B%B8%E7%BA%AA%E5%BD%95%E7%89%87.html](http://104.255.35.132:2348/html/%E5%94%90%E5%B1%B1%E5%A4%A7%E5%9C%B0%E9%9C%87%E7%9C%9F%E7%9B%B8%E7%BA%AA%E5%BD%95%E7%89%87.html) 这个页面出了一个问题：最上面出现了“" />”， 你是用最新版的生成的吗？

**Comment by luckypoem** [comment]
hi.

是啊。是用最新版生成的。不过怎么所发表的帖子并非按时间顺序排列的呢？

**Comment by qibin0506** [comment]
最新版的会过滤到description中的标签。
按照时间排序，这个问题我想想， 下一个版本支持。
