### ISSUE TITLE
windows下如何操作

### ISSUE THREAD

**Issue by zxp0505** [qibin0506/TitanPages#3]
windows下如何操作  ？新手一枚 求教

**Comment by qibin0506** [comment]
直接下载tt.exe就ok

**Comment by ItsSecrets** [comment]
作者您好，我是通过您的博客来到这里。在Windows环境下，我这里的整个工程，然后点击tt.exe会在raw下面生成一个default.md文件。然后content模板我是用的工程demo目录下的模板，但是最终编译生成的html文件排版格式都是靠左对齐的。没有想你的demo中的那个规范排版。

**Comment by qibin0506** [comment]
tt直接点击的话生成的是默认的， 生成的时候需要指定使用的模板文件,最后生成的html文件要放到你静态网页模板规定放到目录才可以， 单独使用html文件可能没有引用到js和css.
你需要在命令行使用tt， 具体方式请看博客或者readme

**Comment by ItsSecrets** [comment]
无意冒犯，我解决问题能力太差了。已经解决了。本地打开我自己生成的html确实是靠左对齐，但是本地打开你demo中的html确是正常排版。我把我自己生成的html文件上传到github排版就正常了。谢谢您百忙之中的解答，已经star

**Comment by FatsoLee** [comment]
你好，windows 下如何使用这些命令行？？？

**Comment by qibin0506** [comment]
@MesaLee  直接下载直接下载tt.exe， 然后再命令行执行。
