### ISSUE TITLE
命令运行不了

### ISSUE THREAD

**Issue by hengyizhangcn** [qibin0506/TitanPages#4]
你这个TT命令在mac 下运行不了

**Comment by hengyizhangcn** [comment]
需要重新编译tt命令
前提是先安装go语言
1.下载安装包https://storage.googleapis.com/golang/go1.7.darwin-amd64.pkg
重启终端，查看版本
go version
配置环境变量

2.下拉https://github.com/qibin0506/TitanPages.git
项目下的tt命令不能直接在mac下运行
在该项目的source文件夹下，有个tt.go源文件，可以自己编译
编译tt.go源文件时，会提示所依赖的项目找不到
项目依赖三个git项目（下载这三个项目，放到所需要的文件夹下），分别是
https://github.com/russross/blackfriday.git
https://github.com/toqueteos/webbrowser.git
https://github.com/shurcooL/sanitized_anchor_name.git
然后运行go build tt.go会生成tt可执行文件
3.运行该可执行文件的方法，如
./tt -help detail

**Comment by qibin0506** [comment]
@hengyizhangcn  如果你的mac版的编译好了， 欢迎pull request到github来。
